#!/bin/bash
if [[ $# -lt 1 ]]; then
  printf "Incorrect usage:\n\t$0 [Number of sales]\n"
  exit
fi
counter=0
readarray -t distributors < distributors.txt
readarray -t products < products.txt
readarray -t prices < prices.txt
readarray -t places < places.txt
while [[ counter -lt $1 ]]; do
  amount=$(( (RANDOM % 100) + 1 ))
  discountPercentage=$(( (RANDOM % 26) ))
  Y=2018
  M=$(( (RANDOM % 12) + 1 ))
  D=$(( (RANDOM % 28) + 1 ))
  index=$(( (RANDOM % ${#distributors[*]}) ))
  distributor=${distributors[$index]}
  index=$(( (RANDOM % ${#products[*]}) ))
  product=${products[$index]}
  totalCash=$((${prices[$index]} * $amount))
  index=$(( (RANDOM % ${#places[*]}) ))
  place=${places[$index]}
  curl -d "{\"amount\": $amount, \"total_cash\": $totalCash, \"discount_percentage\":$discountPercentage, \"Y\":$Y, \"M\":$M, \"D\":$D, \"distributor\":\"$distributor\", \"product\":\"$product\", \"place\":\"$place\"}"  -H "Content-Type: application/json" -X POST http://localhost:5000/sales/create
  counter=$((counter+1))
done
